-- Persistent RAG storage for VECTOR_BACKEND=supabase.
-- Run this once in Supabase SQL Editor.

create extension if not exists vector;

insert into storage.buckets (id, name, public)
values ('compliance-documents', 'compliance-documents', false)
on conflict (id) do nothing;

create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    source text not null,
    page integer,
    content text not null,
    embedding vector(384) not null,
    created_at timestamptz not null default now()
);

create index if not exists document_chunks_embedding_idx
on public.document_chunks
using hnsw (embedding vector_cosine_ops);

create or replace function public.match_document_chunks(
    query_embedding vector(384),
    match_count integer default 4
)
returns table (
    id bigint,
    source text,
    page integer,
    content text,
    similarity real
)
language sql
stable
as $$
    select
        document_chunks.id,
        document_chunks.source,
        document_chunks.page,
        document_chunks.content,
        1 - (document_chunks.embedding <=> query_embedding) as similarity
    from public.document_chunks
    order by document_chunks.embedding <=> query_embedding
    limit least(greatest(match_count, 1), 20);
$$;

grant execute on function public.match_document_chunks(vector(384), integer) to anon, authenticated, service_role;

-- The application should use the server-only Supabase service-role key.
-- Do not expose that key in the browser or static frontend.
-- If you deliberately use an anon key for uploads, add Storage RLS policies
-- that restrict access to this bucket before enabling the cloud backend.
